apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  selector:              # This selector references the label in the Pod
    app: nginx-pod       # template spec for the Deployment
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
